### ISSUE TITLE
Typescript SDK docs are not updated / Examples from docs are broken

### ISSUE THREAD

**Issue by JustAnotherDevv** [apibara/documentation#2]
### Docs are not updated / Examples from docs are broken

[Typescript SDK starter project](https://github.com/apibara/typescript-sdk/tree/main/examples/simple-client) which is mentioned [here](https://app.apibara.com/teams/KCPGymj9Dwm/indexers/DSmmDXycXGq) does not exist or  was deleted and returns 404.

Even basic code examples from [Typescript SDK overview](https://www.apibara.com/docs/typescript-sdk) also don't work after copying and pasting. E.g. the `hash` is used but never declared before.

**Comment by fracek** [comment]
Thank you for reporting this! I will update the sdk and update the docs.

**Comment by robertkodra** [comment]
@fracek The issue still persist on this [page](https://app.apibara.com/teams/lwW3HZeUbDo/indexers/CoUyvSWJEPn)

**Comment by fracek** [comment]
Thank you, I removed the outdated section and linked to the docs while we work on the new dashboard.
